[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.4"
remappings = [
    "verifier-solidity-sdk/=lib/verifier-solidity-sdk/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]